name: vinf_projects
channels:
  - defaults
dependencies:
  - python=3.8
  - jupyter=1.0
  - pandas=1.3
  - matplotlib=3.4.
  - pyspark=3.1
  - pip=21.2.
  - pip:
    - html==1.13
    - findspark==1.4
